server:
  port: 8080
  version: v1
  jwtkey: jwtkey
  admin:
    username: admin
    password: password
  email:
    interval: 60
    host: smtp.qq.com
    port: 587
    username: Aestas16@qq.com
    password: password
  dsn:
redis:
  host: 
  password: 
  db: 0